import datetime
now = datetime.datetime.now()
td = datetime.timedelta(days=1)
print(f'now:{now}')
print(f'timedelta:{td}')
print('----- 加算（timedelta）-----')
print(f'{now} + {td}: = {now + td}')
print('----- 減算（timedelta）-----')
print(f'{now} - {td}: = {now - td}')
print('----- 比較 -----')
print(f'{now} < {now + td}: = {now < (now + td)}')
print(f'{now} > {now + td}: = {now > (now + td)}')
print(f'{now} == {now + td}: = {now == (now + td)}')
print(f'{now} != {now + td}: = {now != (now + td)}')
print('----- 差 -----')
print(datetime.datetime.now() - now)
